name: CI

on: [push]

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - name: get-cmake
              uses: lukka/get-cmake@v3.24.3
            - run: mkdir build
            - run: |
                cd build
                cmake ../src
                cmake --build .
            - run: ./build/Debug/Hello.exe